---
title: "EFA"
author: "Andy Chan"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(haven)
library(tidyverse) 
library(naniar) # missingness
library(car) # for Anova()
library(MVN) # Multivariate normality  
library(QuantPsyc) # Multivariate normality  
library(broom)
library(ggplot2)
library(GGally)
library(CCA)
library(CCP)
library(weights)
library(openxlsx)

# Useful settings
options(digits = 3)


rm(list = ls()) 
dat<- readRDS("Final Kink.rds")
EFA<-dat%>% dplyr::select(COMMUNITY_1:COMMUNITY_6)
EFA <- EFA[complete.cases(EFA),]
# describe(EFA[1:6])

library(psych)
library(GPArotation)
```

# EFA

Community Items: 

"My involvement in the kink community has…

1. ... been generally positive.”
2. ... improved my sex life.”
3. ... taught me to communicate my desires more effectively.”
4. ... taught me to communicate my limits more effectively.”
5. ... taught me the importance of consent.”
6. ... provided opportunities for me to learn about consent.”

```{r}
set.seed(1234) # set seed for reproducability
fa.parallel(EFA, # perform parallel analysis
            fa = "fa",
            fm = "pa",
            show.legend = TRUE,
            main = "Scree Plot and Parallel Analysis")

polychoric_corr <- polychoric(EFA)$rho 

# 
# efa_promax2 <- fa(polychoric_corr, # perform EFA with 6 factors
#                   nfactors=1,
#                   rotate="promax",
#                   fm="pa")
# print(efa_promax2,  cut = 0.4)
# 
# efa_promax2 <- fa(polychoric_corr, # perform EFA with 6 factors
#                   nfactors=2,
#                   rotate="promax",
#                   fm="pa")
# print(efa_promax2,  cut = 0.4)
# 

efa_promax3 <- fa(polychoric_corr, # perform EFA with 6 factors
                  nfactors=3,
                  rotate="promax",
                  fm="pa")
print(efa_promax3)
# efa_promax3$communality

output<-as.data.frame(efa_promax3$Vaccounted)
# output<-rd(output, digits=2)
# library(tibble)
output <- tibble::rownames_to_column(output, "VALUE")

output[2:4]<-rd(output[2:4], digits=2)
# output[2:4]<-lapply(output[2:4], rd, digits=2)
#
fa_table <- function(x, cut) {
  #get sorted loadings
  loadings <- fa.sort(x)$loadings %>% round(3)
  #supress loadings
  loadings[loadings < cut] <- ""
  #get additional info
  add_info <- cbind(x$communality,
                    x$uniquenesses,
                    x$complexity) %>%
    # make it a data frame
    as.data.frame() %>%
    # column names
    rename("Communality" = V1,
           "Uniqueness" = V2,
           "Complexity" = V3) %>%
    #get the item names from the vector
    rownames_to_column("item")
  #build table
  loadings %>%
    unclass() %>%
    as.data.frame() %>%
    rownames_to_column("item") %>%
    left_join(add_info) %>%
    mutate(across(where(is.numeric), round, 3))
}

fatable<-fa_table(efa_promax3,.1) %>% arrange(item)
fatable[5:7]<-lapply(fatable[5:7], rd, digits=2)

EFAResults <- createWorkbook("EFAResults")
addWorksheet(EFAResults, "output")
writeData(EFAResults, sheet = 1, output)
addWorksheet(EFAResults, "fatable")
writeData(EFAResults, sheet = 2, fatable)
saveWorkbook(EFAResults, "EFA Results_4202024.xlsx", overwrite = TRUE)
```
https://statisticsglobe.com/exploratory-factor-analysis-r